### ISSUE TITLE
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. 

### ISSUE THREAD

**Issue by Echoflare** [imjoy-team/imjoy-elfinder#638]
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.5/migration/#basesettings-has-moved-to-pydantic-settings for more details.

![Screenshot_2024-01-31-17-43-21-49_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/imjoy-team/imjoy-elfinder/assets/144500846/dfc8049a-74fa-460e-a80b-81a1a5315bce)

**Comment by oeway** [comment]
should we pin the pydantic version?

**Comment by Echoflare** [comment]
> should we pin the pydantic version?

pydantic version must be under v2.0
