### ISSUE TITLE
Integration with ImJoy

### ISSUE THREAD

**Issue by oeway** [imjoy-team/imjoy-elfinder#94]
I think it's a good time to add some frontend code to enable the integration with imjoy. We can think of two way of integration: 
 * Load imjoy-core to elFinder, and support using ImJoy plugins to visualize and process files.
 * Make elfinder an ImJoy plugin, so we can for example, get rid of this one https://github.com/imjoy-team/jupyter-engine-manager/blob/master/src/ImJoy-elFinder.imjoy.html

https://github.com/imjoy-team/imjoy-core/tree/master

**Comment by MartinHjelmare** [comment]
Number two sounds the best, since we would gather the elfinder responsibility within imjoy-elfinder.
